name: Automation Exercise Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export env variables
        env:
            BASE_URL: ${{ secrets.BASE_URL }}
            USER_EMAIL: ${{ secrets.USER_EMAIL }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          echo "BASE_URL=${BASE_URL}" >> $GITHUB_ENV
          echo "USER_EMAIL=${USER_EMAIL}" >> $GITHUB_ENV
          echo "USER_PASSWORD=${USER_PASSWORD}" >> $GITHUB_ENV

      - name: Run Behave tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o allure-results || true

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update 
          sudo apt-get install allure

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report