name: Automation Exercise Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t auto_exec .

      - name: Run the behave tests in Docker
        run: |
          docker run --name test-run -e BASE_URL="https://automationexercise.com/api/" -e USER_EMAIL="test@test.ie" -e USER_PASSWORD="test1234" auto_exec
          docker cp test-run:/app/allure-results ./allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.12
        with:
          allure_results: ./allure-results
          allure_report: ./allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report